SMT_ITIWithDb/Models/Office.cs
namespace SMT_ITIWithDb.Models
{
    public class Office
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Location { get; set; }
        // Navigation Property 
        public List<Employee> Employees { get; set; }

    }
}

SMT_ITIWithDb/Controllers/OfficeController.cs
using Microsoft.AspNetCore.Mvc;
using SMT_ITIWithDb.Models;

namespace SMT_ITIWithDb.Controllers
{
    public class OfficeController : Controller
    { 
    private EmployeeContext context;
    public OfficeController()
    {
        context = new EmployeeContext();
    }
        public IActionResult Index()
        {
          List<Office>offices=context.Offices.ToList();
            return View(offices);
        }
        public IActionResult Details(int id)
        {
            Office office=context.Offices.SingleOrDefault(o=>o.Id==id);
           return View(office);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost   ]
        public IActionResult Add(Office office)
        {
            context.Offices.Add(office);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Office office = context.Offices.SingleOrDefault(o =>o.Id == id); 

            return View(office); 
        }
        [HttpPost]
        public IActionResult Edit(Office office)
        {
            context.Offices.Update(office);
            context.SaveChanges();
            return RedirectToAction("Index"); 
        }
        public IActionResult Delete(int id)
        {
            Office office = context.Offices.SingleOrDefault(o => o.Id == id);
            context.Offices.Remove(office);
            context.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

SMT_ITIWithDb/Views/Office/Add.cshtml
@model Office
@{
    ViewData["Title"] = "NewForm";
}

<h1>New Employee</h1>

<Form method="post" asp-controller="Office" asp-action="Add">

    <input hidden asp-for="Id"/>
    <label asp-for="Name"></label>
    <input class="form-control form-control-lg" asp-for="Name"  aria-label=".form-control-lg example">
    <br />
    <label asp-for="Location"></label>
    <input class="form-control form-control-lg" asp-for="Location" aria-label=".form-control-lg example" />
    <br />
    <input type="submit" value="Add" class="btn btn-outline-primary" />
</Form>

SMT_ITIWithDb/Views/Office/Details.cshtml
@model Office
@{
    ViewData["Title"] = "Details";
}


<div class="card text-center" style="align-items:center">
    <h1>Office Details</h1>
    <div class="card-body">
        <h5 class="Name">@Model.Name</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Location : @Model.Location</li>
    </ul>
    <div class="card-body">
        <h5><a asp-controller="Office" asp-action="Index"  class="btn btn-outline-primary">Back to list</a></h5>
    </div>
</div>

SMT_ITIWithDb/Views/Office/Edit.cshtml
@model Office

<h1>Edit Office</h1>
<form asp-controller="Office" asp-action="Edit" method="post">

    <input  asp-for="Id" hidden />
    <label asp-for="Name"></label>
    <input class="form-control form-control-lg" aria-label=".form-control-lg example" asp-for="Name"/>
    <br />

    <label asp-for="Location"></label>
    <input class="form-control form-control-lg" aria-label=".form-control-lg example" asp-for="Location"/>
    <br />

    <input type="submit" value="Edit" class=" btn btn-outline-primary" />
</form>

SMT_ITIWithDb/Views/Office/Index.cshtml
@{
    ViewData["Title"] = "Index";
    int index = 1;
}
<h1>The data of Office</h1>
<hr />
<a asp-controller="Office" asp-action="Add" class="btn btn-outline-primary">Add New Office</a>
<hr />

<table class="table table-primary table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Location</th>
         
            <th>Controls</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Office off in Model)
        {
            <tr>
                <td>@(index++)</td>
                <td>@off.Name</td>
                <td>@off.Location</td>
             
                <td>
                    <a asp-controller="Office" asp-action="Details" asp-route-id="@off.Id" ><i class="fa-solid fa-circle-info"></i></a> |
                    <a asp-controller="Office" asp-action="Edit" asp-route-id="@off.Id" ><i class="fa-solid fa-pen-to-square"></i></a> |
                    <a asp-controller="Office" asp-action="Delete" asp-route-id="@off.Id"><i class="fa-solid fa-trash"></i></a> |
                </td>
            </tr>
        }
    </tbody>
</table>