SMT_ITIWithDb/Controllers/ValidationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SMT_ITIWithDb.Models;
using SMT_ITIWithDb.ViewModel;

namespace SMT_ITIWithDb.Controllers
{
    public class ValidationController : Controller
    {
        private EmployeeContext context; 
        public ValidationController()
        {
            context= new EmployeeContext();

        }
        public IActionResult Index()
        {
            List<Employee>employees=context.employees.ToList(); 
            return View(employees);
        }
        [HttpGet]
        public IActionResult Add()
        {
            EmployeeVMcs employee = new EmployeeVMcs()
            {
                Offices = new SelectList(context.Offices, "Id", "Name")
            }; 
            return View(employee);
        }
        [HttpPost]
        public IActionResult Add(EmployeeVMcs employee )
        {
            if (ModelState.IsValid)
            {
                Employee newEmployee = new Employee()
                {
                    Name = employee.Name,
                    Age= employee.Age,
                    Salary= employee.Salary,
                    Img= employee.Img,
                    Email= employee.Email,
                    Password= employee.Password,
                    Office_Id= employee.Office_Id,
                };
                context.employees.Add(newEmployee); 
                context.SaveChanges();
                return RedirectToAction("Index", "Employee");
            }
            employee.Offices = new SelectList(context.Offices,"Id","Name");
            return View(employee);
            
        }
       
    
    }
}

SMT_ITIWithDb/Views/Validation/Add.cshtml
@model EmployeeVMcs
@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<form asp-action="Add" asp-controller="Validation" method="post">
    <div class="mb-2">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-2">
        <label class="form-label" asp-for="Age"></label>
        <input class="form-control" asp-for="Age" />
        <span class="text-danger" asp-validation-for="Age"></span>
    </div>
    <div class="mb-2">
        <label class="form-label" asp-for="Salary"></label>
        <input class="form-control" asp-for="Salary" />
        <span class="text-danger" asp-validation-for="Salary"></span>
    </div>
    <div class="mb-2">
        <label class="form-label" asp-for="Img"></label>
        <input class="form-control" asp-for="Img" />
        <span class="text-danger" asp-validation-for="Img"></span>
    </div>
    <div class="mb-2">
        <label class="form-label" asp-for="Email"></label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>

    <div class="mb-2">
        <label class="form-label" asp-for="Office_Id"></label>
        <select class="form-select" asp-for="Office_Id" asp-items="@Model.Offices"></select>
        <span class="text-danger" asp-validation-for="Office_Id"></span>
    </div>
    <div class="mb-2">
        <label class="form-label" asp-for="Password"></label>
        <input class="form-control" asp-for="Password" />
        <span class="text-danger" asp-validation-for="Password"></span>
    </div>
    <div class="mb-2">
        <label class="form-label" asp-for="ConfirmPassword"></label>
        <input class="form-control" asp-for="ConfirmPassword" />
        <span class="text-danger" asp-validation-for="ConfirmPassword"></span>
    </div>
    <div class="mb-2 text-center">
        <input type="submit" value="Add" class="btn btn-warning" />
    </div>
</form>
@section Scripts{
    <script src="/lib/jquery//dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

SMT_ITIWithDb/Views/Validation/Index.cshtml
@Model Employee
@{
    ViewData["Title"] = "Index";
    int index = 1;
}

<h1>the data of employee with validation </h1>
<a asp-controller="Validation" asp-action="Add" class="btn btn-outline-primary">Add New Employee With Validation </a>
<hr />
<table class="table table-primary table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Image</th>
            <th>Controls</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Employee emp in Model)
        {
            <tr>
                <td>@(index++)</td>
                <td>@emp.Name</td>
                <td>@emp.Email</td>
                <td><img src="/images/@emp.Img" alt="student image" style="width:100px" /></td>
                <td>
                    <a href="/Employee/Details/@emp.Id"><i class="fa-solid fa-circle-info"></i></a> |
                    <a href="/Employee/EditForm/@emp.Id"><i class="fa-solid fa-pen-to-square"></i></a> |
                    <a href="/Employee/Delete/@emp.Id"><i class="fa-solid fa-trash"></i></a> |
                </td>
            </tr>
        }
    </tbody>
</table>